name: CI/CD React APP

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install CI
        run: npm ci

      - name: Build the project
        run: npm run build

        #Configue Git Identity
      - name: Configure Git
        run: 
          git config --global user.name Nandhu20-06
          git config --global user.email nandithatadiparthi23@gmail.com

      #Deploy into Github Pages
      - name: Deployment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run:
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          npm run deploy
